modLoader="javafml" 
loaderVersion="[31,)" 
#issueTrackerURL="" 
[[mods]] 
modId="php" 
version="${file.jarVersion}" 
displayName="PointedHP Mod" 
#updateJSONURL="" 
#displayURL="" 
credits="VidTu" 
authors="Lixty" 
description=''''''
[[dependencies.php]] 
    modId="forge" 
    mandatory=true 
    versionRange="[31,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.php]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
